import { Platform, StyleSheet } from 'react-native';
import type { ThemeColors } from '@/constants/theme';
import { scaleFont, scaleHeight, scaleWidth } from '@/utils/responsive';

export const createUploadStyles = (colors: ThemeColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: scaleHeight(60),
    paddingHorizontal: scaleWidth(20),
    paddingBottom: scaleHeight(16),
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitle: {
    fontSize: Platform.OS === 'android' ? scaleFont(16): scaleFont(18),
    fontWeight: '700',
    color: colors.text,
  },
  publishButton: {
    backgroundColor: colors.primary,
    borderRadius: scaleWidth(12),
    paddingHorizontal: scaleWidth(14),
    paddingVertical: scaleHeight(10),
    minWidth: scaleWidth(110),
    alignItems: 'center',
    justifyContent: 'center',
  },
  publishButtonDisabled: {
    opacity: 0.6,
  },
  publishButtonText: {
    fontSize: scaleFont(14),
    fontWeight: '800',
    color: colors.textOnPrimary,
  },
  publishToastWrapper: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    zIndex: 9999,
    elevation: 9999,
  },
  welcomeAvatarWrap: {
    width: scaleWidth(60),
    height: scaleWidth(60),
    borderRadius: scaleWidth(30),
    overflow: 'hidden',
    backgroundColor: 'rgba(205, 127, 50, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(205, 127, 50, 0.25)',
  },
  welcomeAvatar: {
    width: '100%',
    height: '100%',
  },
  publishToastBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  wizardFooter: {
    flexDirection: 'row',
    gap: scaleWidth(12),
    paddingHorizontal: scaleWidth(20),
    paddingVertical: scaleHeight(16),
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.background,
  },
  wizardButton: {
    flex: 1,
    paddingVertical: scaleHeight(14),
    borderRadius: scaleWidth(12),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  wizardButtonSecondary: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  wizardButtonText: {
    fontSize: scaleFont(15),
    fontWeight: '700',
    color: colors.textOnPrimary,
  },
  summaryValueText: {
    fontSize: scaleFont(14),
    fontWeight: '600',
    color: colors.textSecondary,
    marginTop: scaleHeight(6),
  },
  wizardButtonTextSecondary: {
    color: colors.text,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: scaleWidth(20),
  },
  authGateCard: {
    marginTop: scaleHeight(20),
    backgroundColor: colors.surface,
    borderRadius: scaleWidth(16),
    padding: scaleWidth(20),
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  authGateTitle: {
    fontSize: Platform.OS === 'android' ? scaleFont(18): scaleFont(20),
    fontWeight: '800',
    color: colors.text,
    marginBottom: scaleHeight(6),
  },
  authGateDescription: {
    fontSize: Platform.OS === 'android' ? scaleFont(12): scaleFont(14),
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: scaleFont(20),
    marginBottom: scaleHeight(14),
  },
  authGateButton: {
    width: '100%',
    backgroundColor: colors.primary,
    paddingVertical: scaleHeight(14),
    borderRadius: scaleWidth(12),
    alignItems: 'center',
    marginBottom: scaleHeight(12),
  },
  authGateButtonText: {
    color: colors.textOnPrimary,
    fontSize: Platform.OS === 'android' ? scaleFont(14): scaleFont(16),
    fontWeight: '700',
  },
  authGateLink: {
    color: colors.secondary,
    fontSize: Platform.OS === 'android' ? scaleFont(12): scaleFont(14),
    fontWeight: '700',
  },
  sectionTitle: {
    fontSize: Platform.OS === 'android' ? scaleFont(16): scaleFont(18),
    fontWeight: '700',
    color: colors.text,
    marginBottom: scaleHeight(8),
  },
  sectionDescription: {
    fontSize: Platform.OS === 'android' ? scaleFont(12): scaleFont(14),
    color: colors.textSecondary,
    marginBottom: scaleHeight(32),
    lineHeight: scaleFont(22),
  },
  optionsContainer: {
    gap: scaleWidth(16),
  },
  uploadOption: {
    backgroundColor: colors.surface,
    borderRadius: scaleWidth(16),
    padding: scaleWidth(24),
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  uploadOptionIcon: {
    width: scaleWidth(64),
    height: scaleWidth(64),
    borderRadius: scaleWidth(32),
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: scaleHeight(16),
  },
  uploadOptionTitle: {
    fontSize: Platform.OS === 'android' ? scaleFont(16): scaleFont(18),
    fontWeight: '700',
    color: colors.text,
    marginBottom: scaleHeight(4),
  },
  uploadOptionDescription: {
    fontSize: Platform.OS === 'android' ? scaleFont(12): scaleFont(14),
    color: colors.textSecondary,
    textAlign: 'center',
  },
  disabledText: {
    color: colors.textSecondary,
    opacity: 0.5,
  },
  form: {
    flex: 1,
    padding: scaleWidth(20),
  },
  formSection: {
    marginBottom: scaleHeight(24),
  },
  imageDropzone: {
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: 'dashed',
    borderRadius: scaleWidth(12),
    paddingVertical: scaleHeight(16),
    paddingHorizontal: scaleWidth(12),
    backgroundColor: colors.surface,
  },
  imageDropzoneText: {
    fontSize: Platform.OS === 'android' ? scaleFont(12): scaleFont(14),
    fontWeight: '800',
    color: colors.text,
  },
  imageDropzoneHint: {
    marginTop: scaleHeight(6),
    fontSize: Platform.OS === 'android' ? scaleFont(10): scaleFont(12),
    color: colors.textSecondary,
  },
  imageThumbRow: {
    marginTop: scaleHeight(10),
  },
  imageThumbWrap: {
    marginRight: scaleWidth(10),
    borderRadius: scaleWidth(10),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
  },
  imageThumb: {
    width: scaleWidth(80),
    height: scaleWidth(80),
  },
  imageUploadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderRadius: scaleWidth(12),
  },
  imageThumbRemove: {
    position: 'absolute',
    top: scaleWidth(6),
    right: scaleWidth(6),
    width: scaleWidth(22),
    height: scaleWidth(22),
    borderRadius: scaleWidth(11),
    backgroundColor: 'rgba(0,0,0,0.65)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaleWidth(12),
  },
  checkbox: {
    width: scaleWidth(22),
    height: scaleWidth(22),
    borderRadius: scaleWidth(6),
    borderWidth: 1,
    borderColor: 'black',
    backgroundColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkboxTextWrap: {
    flex: 1,
  },
  helperText: {
    fontSize: Platform.OS === 'android' ? scaleFont(10): scaleFont(12),
    color: colors.textSecondary,
    marginTop: scaleHeight(4),
  },
  amenitiesChipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: scaleWidth(8),
    marginTop: scaleHeight(10),
  },
  amenitiesChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaleWidth(6),
    paddingVertical: scaleHeight(8),
    paddingHorizontal: scaleWidth(10),
    borderRadius: scaleWidth(999),
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    maxWidth: '100%',
  },
  amenitiesChipText: {
    color: colors.text,
    fontSize: Platform.OS === 'android' ? scaleFont(10): scaleFont(12),
    fontWeight: '700',
    maxWidth: scaleWidth(220),
  },
  modalFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: scaleWidth(14),
    paddingVertical: scaleHeight(12),
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  modalDoneButton: {
    backgroundColor: colors.primary,
    borderRadius: scaleWidth(12),
    paddingVertical: scaleHeight(12),
    alignItems: 'center',
  },
  modalDoneButtonText: {
    color: colors.textOnPrimary,
    fontSize: Platform.OS === 'android' ? scaleFont(12): scaleFont(14),
    fontWeight: '800',
  },
  formLabel: {
    fontSize: scaleFont(15),
    fontWeight: '600',
    color: colors.text,
    marginBottom: scaleHeight(8),
  },
  formLabelSmall: {
    fontSize: scaleFont(13),
    fontWeight: '700',
    color: colors.textSecondary,
    marginBottom: scaleHeight(6),
  },
  input: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: scaleWidth(12),
    paddingHorizontal: scaleWidth(16),
    paddingVertical: scaleHeight(14),
    fontSize: scaleFont(16),
    color: colors.text,
  },
  textArea: {
    minHeight: scaleHeight(120),
    paddingTop: scaleHeight(14),
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: scaleWidth(8),
  },
  chip: {
    paddingVertical: scaleHeight(10),
    paddingHorizontal: scaleWidth(18),
    borderRadius: scaleWidth(20),
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  chipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipText: {
    fontSize: scaleFont(14),
    fontWeight: '500',
    color: colors.text,
  },
  chipTextSelected: {
    color: colors.textOnPrimary,
  },
  radioRow: {
    flexDirection: 'column',
    //gap: scaleWidth(26),
    flexWrap: 'wrap',
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaleWidth(8),
    paddingVertical: scaleHeight(10),
    paddingHorizontal: scaleWidth(16),
    borderRadius: scaleWidth(12),
    borderWidth: 1,
    borderColor: colors.border,
    marginLeft: scaleWidth(8),
    width: "90%",
    height: scaleHeight(80),
    marginTop: scaleHeight(20),
  },
  radioOptionSelected: {
    borderColor: colors.primary,
  },
  radioOuter: {
    width: scaleWidth(20),
    height: scaleWidth(20),
    borderRadius: scaleWidth(10),
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  radioOuterSelected: {
    borderColor: colors.primary,
  },
  radioInner: {
    width: scaleWidth(10),
    height: scaleWidth(10),
    borderRadius: scaleWidth(5),
    backgroundColor: colors.primary,
  },
  radioLabel: {
    fontSize: scaleFont(14),
    fontWeight: '600',
    color: colors.text,
  },
  formRow: {
    flexDirection: 'row',
    gap: scaleWidth(16),
    marginBottom: scaleHeight(24),
  },
  formColumn: {
    flex: 1,
  },
  locationInput: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: scaleWidth(12),
    paddingHorizontal: scaleWidth(16),
    paddingVertical: scaleHeight(14),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectRight: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: scaleWidth(10),
  },
  locationInputText: {
    fontSize: scaleFont(16),
    color: colors.text,
  },
  placeholder: {
    color: colors.textSecondary,
  },
  toastContainer: {
    position: 'absolute',
    top: scaleHeight(64),
    left: scaleWidth(16),
    right: scaleWidth(16),
    alignItems: 'center',
    zIndex: 9999,
    elevation: 9999,
  },
  toastInner: {
    backgroundColor: 'rgba(0,0,0,0.85)',
    paddingVertical: scaleHeight(10),
    paddingHorizontal: scaleWidth(14),
    borderRadius: scaleWidth(10),
    maxWidth: '100%',
  },
  toastText: {
    color: '#fff',
    fontSize: scaleFont(13),
    fontWeight: '800',
  },

  publishingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255,255,255,0.92)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
  },
  publishingOverlayText: {
    marginTop: scaleHeight(12),
    fontSize: scaleFont(14),
    fontWeight: '800',
    color: colors.text,
  },

  bottomPadding: {
    height: scaleHeight(120),
  },
  editContent: {
    flex: 1,
  },
  videoPreviewContainer: {
    width: '100%',
    aspectRatio: 9/16,
    backgroundColor: colors.text,
    borderRadius: scaleWidth(16),
    overflow: 'hidden',
    marginBottom: scaleHeight(24),
    position: 'relative',
  },
  videoPreview: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  textOverlayPreview: {
    position: 'absolute',
    left: 0,
    right: 0,
    paddingHorizontal: scaleWidth(16),
    paddingVertical: scaleHeight(12),
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    alignItems: 'center',
  },
  textTop: {
    top: scaleHeight(20),
  },
  textCenter: {
    top: '50%',
    marginTop: -scaleHeight(20),
  },
  textBottom: {
    bottom: scaleHeight(20),
  },
  overlayTextPreview: {
    fontWeight: '700',
    textAlign: 'center',
  },
  controlSection: {
    marginBottom: scaleHeight(20),
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: scaleHeight(12),
  },
  modalHeaderSpacer: {
    width: scaleWidth(24),
  },
  modalHeaderCloseButton: {
    width: scaleWidth(24),
    height: scaleWidth(24),
    alignItems: 'center',
    justifyContent: 'center',
  },
  controlTitle: {
    fontSize: scaleFont(18),
    fontWeight: '700',
    color: colors.text,
    marginBottom: scaleHeight(12),
  },
  textInput: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: scaleWidth(12),
    paddingHorizontal: scaleWidth(16),
    paddingVertical: scaleHeight(14),
    fontSize: scaleFont(16),
    color: colors.text,
    marginBottom: scaleHeight(16),
  },
  controlSubsection: {
    marginBottom: scaleHeight(16),
  },
  controlLabel: {
    fontSize: scaleFont(14),
    fontWeight: '600',
    color: colors.text,
    marginBottom: scaleHeight(8),
  },
  buttonGroup: {
    flexDirection: 'row',
    gap: scaleWidth(8),
  },
  controlButton: {
    flex: 1,
    paddingVertical: scaleHeight(10),
    paddingHorizontal: scaleWidth(12),
    borderRadius: scaleWidth(8),
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
  },
  controlButtonSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  controlButtonText: {
    fontSize: scaleFont(13),
    fontWeight: '600',
    color: colors.text,
  },
  controlButtonTextSelected: {
    color: colors.textOnPrimary,
  },
  editFooter: {
    paddingHorizontal: scaleWidth(20),
    paddingVertical: scaleHeight(16),
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.background,
  },
  continueButton: {
    backgroundColor: colors.primary,
    borderRadius: scaleWidth(12),
    paddingVertical: scaleHeight(14),
    alignItems: 'center',
  },
  continueButtonText: {
    fontSize: scaleFont(16),
    fontWeight: '700',
    color: colors.textOnPrimary,
  },
  deleteButton: {
    fontSize: scaleFont(16),
    fontWeight: '600',
    color: '#FF3B30',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
    alignItems: 'center',
    zIndex: 9999,
    elevation: 9999,
  },
  locationModal: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
    alignItems: 'center',
    zIndex: 9999,
    elevation: 9999,
  },
  modal: {
    width: '100%',
    backgroundColor: colors.background,
    paddingHorizontal: scaleWidth(20),
    paddingVertical: scaleHeight(24),
    borderTopLeftRadius: scaleWidth(20),
    borderTopRightRadius: scaleWidth(20),
  },
  modalTitle: {
    fontSize: scaleFont(18),
    fontWeight: '700',
    color: colors.text,
    marginBottom: 8,
  },
  modalDescription: {
    fontSize: scaleFont(14),
    color: colors.textSecondary,
    marginBottom: scaleHeight(24),
    lineHeight: scaleFont(20),
  },
  modalButtonGroup: {
    flexDirection: 'row',
    gap: scaleWidth(12),
  },
  modalButton: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: scaleWidth(12),
    paddingVertical: scaleHeight(14),
    alignItems: 'center',
  },
  modalButtonSecondary: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalButtonText: {
    fontSize: scaleFont(16),
    fontWeight: '700',
    color: colors.textOnPrimary, 
  },
  modalButtonTextSecondary: {
    fontSize: scaleFont(16),
    fontWeight: '700',
    color: colors.text,
  },

  disabledInput: {
    opacity: 0.7,
  },
  pickerItem: {
    paddingVertical: scaleHeight(14),
  },
  pickerItemText: {
    fontSize: scaleFont(16),
    fontWeight: '600',
    color: colors.text,
  },
  listSeparator: {
    height: 1,
    backgroundColor: colors.border,
    opacity: 0.2,
  },
  emptyPickerText: {
    paddingVertical: scaleHeight(16),
    color: colors.textSecondary,
  },
  emptyPickerContainer: {
    paddingHorizontal: scaleWidth(16),
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: scaleHeight(20),
    gap: scaleHeight(12),
  },
  emptyPickerActionButton: {
    backgroundColor: colors.primary,
    paddingVertical: scaleHeight(12),
    paddingHorizontal: scaleWidth(18),
    borderRadius: scaleWidth(10),
  },
  emptyPickerActionButtonText: {
    color: '#fff',
    fontSize: scaleFont(14),
    fontWeight: '800',
  },
  amenityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: scaleHeight(12),
    paddingHorizontal: scaleWidth(12),
  },
  amenityLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaleWidth(10),
    flexShrink: 1,
  },
  amenityIcon: {
    width: scaleWidth(22),
    height: scaleWidth(22),
    resizeMode: 'contain',
  },
  amenityIconFallback: {
    width: scaleWidth(22),
    height: scaleWidth(22),
    borderRadius: scaleWidth(6),
    backgroundColor: colors.border,
  },
  amenityCheck: {
    width: scaleWidth(22),
    height: scaleWidth(22),
    borderRadius: scaleWidth(6),
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  amenityCheckSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  searchInput: {
    marginTop: scaleHeight(12),
    marginBottom: scaleHeight(8),
  },

  offPlanItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaleWidth(12),
    paddingVertical: scaleHeight(12),
  },
  offPlanThumb: {
    width: scaleWidth(80),
    height: scaleWidth(68),
    borderRadius: scaleWidth(10),
    overflow: 'hidden',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  offPlanThumbImage: {
    width: '100%',
    height: '100%',
  },
  offPlanThumbPlaceholder: {
    flex: 1,
    backgroundColor: colors.border,
    opacity: 0.25,
  },
  offPlanTitle: {
    flex: 1,
    fontSize: scaleFont(15),
    fontWeight: '600',
    color: colors.text,
  },

  highlightsOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 0,
    // Android: ensure it stays behind the sheet
    elevation: 0,
  },
  highlightsSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.background,
    borderTopLeftRadius: scaleWidth(20),
    borderTopRightRadius: scaleWidth(20),
    overflow: 'hidden',
    zIndex: 1,
    elevation: 1,
  },
  highlightsHeader: {
    paddingHorizontal: scaleWidth(16),
    paddingVertical: scaleHeight(14),
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  highlightsTitle: {
    fontSize: scaleFont(16),
    fontWeight: '800',
    color: colors.text,
  },
  highlightsBack: {
    fontSize: scaleFont(14),
    fontWeight: '700',
    color: colors.primary,
  },
  highlightsClose: {
    fontSize: scaleFont(14),
    fontWeight: '700',
    color: colors.textSecondary,
  },
  highlightsVideoContainer: {
    width: '100%',
    alignSelf: 'stretch',
    // Fill available space above the highlight controls.
    flex: 1,
    minHeight: 0,
    backgroundColor: '#000',
    borderRadius: 0,
    overflow: 'hidden',
  },
  highlightsVideo: {
    width: '100%',
    height: '100%',
    flex: 1,
    alignSelf: 'stretch',
  },
  highlightsVideoControls: {
    position: 'absolute',
    // Lift controls above the scrubber overlay
    bottom: scaleHeight(56),
    left: scaleWidth(10),
    flexDirection: 'row',
    gap: scaleWidth(10),
    zIndex: 8,
    elevation: 8,
  },
  highlightsVideoControlButton: {
    width: scaleWidth(40),
    height: scaleWidth(40),
    borderRadius: scaleWidth(20),
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Overlay layer for edit preview controls/text (tap handler is a separate absolute Pressable)
  editPreviewControlsOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 999,
    elevation: 999,
  },

  previewActionsRow: {
    flexDirection: 'row',
    gap: scaleWidth(12),
    paddingHorizontal: scaleWidth(16),
    paddingVertical: scaleHeight(14),
  },
  previewActionButton: {
    flex: 1,
    paddingVertical: scaleHeight(14),
    borderRadius: scaleWidth(12),
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewActionPrimary: {
    backgroundColor: colors.primary,
  },
  previewActionPrimaryText: {
    color: colors.textOnPrimary,
    fontWeight: '800',
    fontSize: scaleFont(14),
  },
  previewActionSecondary: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  previewActionSecondaryText: {
    color: colors.text,
    fontWeight: '800',
    fontSize: scaleFont(14),
  },
  highlightsScroll: {
    flex: 1,
  },
  highlightsContent: {
    paddingHorizontal: scaleWidth(16),
    paddingTop: scaleHeight(10),
    gap: scaleHeight(10),
    // Let the controls take only the space they need; video fills the rest.
    flexGrow: 0,
    flexShrink: 0,
  },
  highlightsPicker: {
    paddingRight: scaleWidth(16),
    gap: scaleWidth(8),
  },
  highlightsPickerChip: {
    paddingHorizontal: scaleWidth(14),
    paddingVertical: scaleHeight(8),
    borderRadius: scaleWidth(2),
    borderBottomWidth: 2.5,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  highlightsPickerChipActive: {
    //backgroundColor: colors.primary,
    borderBottomColor: colors.primary,
  },
  highlightsPickerChipText: {
    fontSize: scaleFont(13),
    fontWeight: '800',
    color: colors.text,
  },
  highlightsPickerChipTextActive: {
    color: colors.primary,
  },
  highlightsVideoOuter: {
    width: '100%',
    // Give the video more of the sheet height so there's no unused white area below.
    flex: 2,
    minHeight: 0,
    alignSelf: 'stretch',
    // Ensure no inset around the edge-to-edge video.
    paddingHorizontal: 0,
    marginHorizontal: 0,
    marginTop: 0,
  },
  highlightsScrubberOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: scaleWidth(10),
    paddingBottom: scaleHeight(10),
    paddingTop: scaleHeight(10),
    backgroundColor: 'rgba(0,0,0,0.35)',
    zIndex: 4,
    elevation: 4,
  },
  highlightsNudgeZoneLeft: {
    position: 'absolute',
    top: 0,
    // Don't overlap the scrubber overlay at the bottom (so dragging is easy).
    bottom: scaleHeight(60),
    left: 0,
    width: scaleWidth(20),
    // Keep these zones behind the scrubber overlay so they can't steal scrub gestures.
    zIndex: 3,
  },
  highlightsNudgeZoneRight: {
    position: 'absolute',
    top: 0,
    // Don't overlap the scrubber overlay at the bottom (so dragging is easy).
    bottom: scaleHeight(60),
    right: 0,
    width: scaleWidth(20),
    // Keep these zones behind the scrubber overlay so they can't steal scrub gestures.
    zIndex: 3,
  },
  highlightsTimeRowOverlay: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: scaleHeight(6),
  },
  highlightsTimeTextOverlay: {
    fontSize: scaleFont(12),
    fontWeight: '800',
    color: colors.textOnPrimary,
  },
  highlightsCirclePicker: {
    paddingTop: scaleHeight(2),
    paddingBottom: 0,
    gap: scaleWidth(14),
    paddingRight: scaleWidth(16),
    flexDirection: 'row',
    alignItems: 'center',
  },
  highlightsCircleItem: {
    alignItems: 'center',
    width: scaleWidth(72),
  },
  highlightsCircle: {
    width: scaleWidth(54),
    height: scaleWidth(54),
    borderRadius: scaleWidth(27),
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  highlightsCircleActive: {
    backgroundColor: colors.surface,
    borderColor: colors.primary,
  },
  highlightsCircleAdd: {
    width: scaleWidth(54),
    height: scaleWidth(54),
    borderRadius: scaleWidth(27),
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  highlightsCircleAddText: {
    fontSize: scaleFont(26),
    fontWeight: '400',
    color: colors.primary,
    marginTop: -2,
  },
  highlightsAddOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: scaleWidth(20),
  },
  highlightsAddModal: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: colors.background,
    borderRadius: scaleWidth(16),
    padding: scaleWidth(16),
  },
  highlightsAddTitle: {
    fontSize: scaleFont(16),
    fontWeight: '800',
    color: colors.text,
    marginBottom: scaleHeight(12),
  },
  highlightsAddGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    gap: scaleWidth(14),
  },
  highlightsAddCircleItem: {
    width: scaleWidth(86),
    alignItems: 'center',
    marginBottom: scaleHeight(10),
  },
  highlightsAddCircle: {
    width: scaleWidth(64),
    height: scaleWidth(64),
    borderRadius: scaleWidth(32),
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  highlightsAddCircleLabel: {
    marginTop: scaleHeight(8),
    fontSize: scaleFont(13),
    fontWeight: '800',
    color: colors.text,
    textAlign: 'center',
  },
  highlightsAddCancel: {
    marginTop: scaleHeight(14),
    paddingVertical: scaleHeight(12),
    alignItems: 'center',
    borderRadius: scaleWidth(12),
    borderWidth: 1,
    borderColor: colors.border,
  },
  highlightsAddCancelText: {
    fontSize: scaleFont(14),
    fontWeight: '800',
    color: colors.textSecondary,
  },
  highlightsCircleTime: {
    marginTop: scaleHeight(6),
    fontSize: scaleFont(10),
    fontWeight: '800',
    color: colors.textSecondary,
  },
  highlightsCircleTimeActive: {
    color: colors.primary,
  },
  highlightsDoneButton: {
    flex: 1,
    marginTop: 0,
    backgroundColor: colors.primary,
    // borderWidth:1,
    // borderColor: colors.primary,
    borderRadius: scaleWidth(12),
    paddingVertical: scaleHeight(12),
    alignItems: 'center',
  },
  highlightsDoneButtonText: {
    color: colors.textOnPrimary,
    fontSize: scaleFont(14),
    fontWeight: '800',
  },
  highlightsBody: {
    paddingTop: scaleHeight(2),
  },
  highlightsStepTitle: {
    fontSize: scaleFont(16),
    fontWeight: '800',
    color: colors.text,
     marginTop: scaleHeight(14),
  },
  highlightsStepSubtitle: {
    //marginTop: scaleHeight(2),
    marginBottom: scaleHeight(8),
    fontSize: scaleFont(12),
    color: colors.textSecondary,
    lineHeight: scaleFont(18),
  },
  highlightsActionsRow: {
    marginTop: scaleHeight(14),
    flexDirection: 'row',
    gap: scaleWidth(12),
  },
  highlightsSelectButton: {
    flex: 1,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: scaleWidth(12),
    paddingVertical: scaleHeight(12),
    alignItems: 'center',
    marginTop: 0,
  },
  highlightsSelectButtonText: {
    color: colors.primary,
    fontSize: scaleFont(14),
    fontWeight: '800',
  },
  highlightsNextButton: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: scaleWidth(12),
    paddingVertical: scaleHeight(12),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  highlightsNextButtonText: {
    color: colors.text,
    fontSize: scaleFont(14),
    fontWeight: '800',
  },
});
